name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ./k6-tests/load-test.js

      - name: Save k6 results as JSON
        run: k6 run --out json=results.json ./k6-tests/load-test.js

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: results.json
