name: Security Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run OWASP ZAP Baseline Scan
        run: |
          chmod +x ./zap-tests/zap-scan.sh
          ./zap-tests/zap-scan.sh

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.json
