name: Python Sample CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      flask:
        image: python:3.10
        ports:
          - 5000:5000
        options: --name flask-service
        volumes:
          - ${{ github.workspace }}:/app
        command: bash -c "cd /app && pip install -r requirements.txt && python app.py"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Unit + Integration
      - name: Run Pytest (Unit + Integration)
        run: pytest tests/unit tests/integration --junitxml=results.xml

      # API
      - name: Run API Tests
        run: pytest tests/api --junitxml=results-api.xml

      # Performance (Locust headless mode)
      - name: Run Locust Load Test
        run: locust -f tests/performance/locustfile.py --host=http://localhost:5000 --headless -u 10 -r 2 -t 30s
